services:
  zabbix-server:
    extends:
      file: compose_zabbix_components.yaml
      service: server-pgsql
    image: "${ZABBIX_SERVER_PGSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    depends_on:
      - postgres-server
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend  # Dodanie serwera do wspólnej sieci frontend

  zabbix-proxy-sqlite3:
    extends:
      file: compose_zabbix_components.yaml
      service: proxy-sqlite3
    image: "${ZABBIX_PROXY_SQLITE3_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-proxy-mysql:
    extends:
      file: compose_zabbix_components.yaml
      service: proxy-mysql
    image: "${ZABBIX_PROXY_MYSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    depends_on:
      - mysql-server
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-web-apache-pgsql:
    extends:
      file: compose_zabbix_components.yaml
      service: web-apache-pgsql
    image: "${ZABBIX_WEB_APACHE_PGSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    depends_on:
      - postgres-server
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-web-nginx-pgsql:
    extends:
      file: compose_zabbix_components.yaml
      service: web-nginx-pgsql
    image: "${ZABBIX_WEB_NGINX_PGSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    depends_on:
      - postgres-server
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-agent:
    extends:
      file: compose_zabbix_components.yaml
      service: agent
    image: "${ZABBIX_AGENT_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    environment:
      - ZBX_SERVER_HOST=zabbix-server  # Ustawienie serwera Zabbix
      - ZBX_HOSTNAME=zabbix-agent       # Ustawienie nazwy hosta dla agenta
    networks:
      - frontend  # Dodanie agenta do tej samej sieci frontend

  zabbix-java-gateway:
    extends:
      file: compose_zabbix_components.yaml
      service: java-gateway
    image: "${ZABBIX_JAVA_GATEWAY_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-snmptraps:
    extends:
      file: compose_zabbix_components.yaml
      service: snmptraps
    image: "${ZABBIX_SNMPTRAPS_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  zabbix-web-service:
    extends:
      file: compose_zabbix_components.yaml
      service: web-service
    image: "${ZABBIX_WEB_SERVICE_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    labels:
      com.zabbix.os: "${UBUNTU_OS_TAG}"
    networks:
      - frontend

  mysql-server:
    profiles:
      - all
    extends:
      file: compose_databases.yaml
      service: mysql-server

  postgres-server:
    extends:
      file: compose_databases.yaml
      service: postgres-server

  db-data-mysql:
    profiles:
      - all
    extends:
      file: compose_databases.yaml
      service: db-data-mysql

  db-data-pgsql:
    extends:
      file: compose_databases.yaml
      service: db-data-pgsql

  elasticsearch:
    extends:
      file: compose_databases.yaml
      service: elasticsearch

  selenium:
    extends:
      file: compose_additional_components.yaml
      service: selenium

  selenium-chrome:
    platform: linux/amd64
    extends:
      file: compose_additional_components.yaml
      service: selenium-chrome

  selenium-firefox:
    extends:
      file: compose_additional_components.yaml
      service: selenium-firefox

networks:
  frontend:
    driver: bridge  # Wspólna sieć dla serwera i agenta

  backend:
    driver: bridge
    internal: true

  database:
    driver: bridge
    internal: true

  tools_frontend:
    driver: bridge

volumes:
  snmptraps:

secrets:
  MYSQL_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.MYSQL_ROOT_PASSWORD
  POSTGRES_USER:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_PASSWORD
